### ISSUE TITLE
Exception on server start

### ISSUE THREAD

**Issue by izatwin** [Jikoo/OpenInv#162]
Getting an error when loading the most recent version 4.4.0
Paper version: 1.20.1-196

Caused by: java.util.zip.ZipException: zip END header not found
This issue is not present in openinv 4.3.1
Let me know if you need more information

`java.lang.RuntimeException: Directory 'plugins/OpenInv-4.4.0.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.20.1.jar:git-Paper-196]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.Main.main(Main.java:137) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:51) ~[paper-1.20.1.jar:git-Paper-196]
        ... 20 more`

**Comment by Jikoo** [comment]
Unable to reproduce. Please try re-downloading OpenInv, sounds like the file you downloaded got corrupted.

**Comment by Jikoo** [comment]
Closing due to lack of response. If this issue persists after re-downloading OpenInv, let me know and we can reopen this and try other fixes.
