### ISSUE TITLE
Using the /inv command crashes server for 1.17

### ISSUE THREAD

**Issue by Mori01231** [Jikoo/OpenInv#26]
Using this release ( https://github.com/Jikoo/OpenInv/releases/tag/4.1.8 ) on the first spigot 1.17 build 
Produces following error which crashes the server when using the /inv command to check a player's inventory
```
[15:15:29] [Server thread/WARN]: [OpenInv] Task #301 for OpenInv v4.1.8 generated an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at net.minecraft.core.NonNullList.get(SourceFile:46) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.inventory.Container.b(Container.java:272) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.inventory.Container.d(Container.java:228) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.inventory.Container.addSlotListener(Container.java:161) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.level.EntityPlayer.initMenu(EntityPlayer.java:545) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at com.lishid.openinv.internal.v1_17_R1.PlayerDataManager.openInventory(PlayerDataManager.java:175) ~[?:?]
        at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:282) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:173) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1251) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:15:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1309) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at net.minecraft.core.NonNullList.get(SourceFile:46) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.inventory.Container.b(Container.java:272) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.inventory.Container.d(Container.java:228) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.level.EntityPlayer.tick(EntityPlayer.java:588) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.level.World.a(World.java:692) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1296) ~[spigot-1.17.jar:3104-Spigot-a09c0bb-d747f8e]
        ... 5 more        
```

**Comment by Jikoo** [comment]
Update Spigot.
