### ISSUE TITLE
Error while executing command /openender

### ISSUE THREAD

**Issue by NonpawitE** [Jikoo/OpenInv#29]
java.lang.InstantiationException: Unable to create a new ISpecialEnderChest: null
        at com.lishid.openinv.util.InternalAccessor.newSpecialEnderChest(InternalAccessor.java:196)
        at com.lishid.openinv.OpenInv.getSpecialEnderChest(OpenInv.java:216)
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:165)
        at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34)
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:97)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:462)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1005)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:951)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:766)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Jikoo** [comment]
Update Spigot.
