### ISSUE TITLE
Error occurred while enabling OpenInv v4.1.8

### ISSUE THREAD

**Issue by Redlnn** [Jikoo/OpenInv#30]
I am using the latest paperclip server, and the following error is output when the server start.

```
[12:42:23 INFO]: Starting minecraft server version 1.17
[12:42:23 INFO]: This server is running Paper version git-Paper-"ce66102" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[12:42:27 INFO]: [OpenInv] Loading OpenInv v4.1.8
[12:42:43 INFO]: [OpenInv] Enabling OpenInv v4.1.8
[12:42:43 ERROR]: Error occurred while enabling OpenInv v4.1.8 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/entity/player/PlayerInventory
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:192) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.lishid.openinv.util.InternalAccessor.<init>(InternalAccessor.java:43) ~[?:?]
        at com.lishid.openinv.OpenInv.onEnable(OpenInv.java:358) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:303) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.player.PlayerInventory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[Paper-Server-1.17-R0.1-SNAPSHOT-mojang-mapped.jar:git-Paper-"ce66102"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 22 more
[12:42:43 INFO]: [OpenInv] Disabling OpenInv v4.1.8
```

**Comment by Jikoo** [comment]
Cannot reproduce. Make sure you're not using arguments that result in a server jar that isn't re-obfuscated.

**Comment by Redlnn** [comment]
Thanks for the reminder, there will be no problems
