### ISSUE TITLE
/oe and /open ender doesen't works

### ISSUE THREAD

**Issue by FLORIAN4600** [Jikoo/OpenInv#39]
Hi,
I have a problem with this plugin,
when i put /oe <player_name> in the chat the plugin said:
[17:36:05 WARN]: java.lang.InstantiationException: Unable to create a new ISpecialEnderChest: null
[17:36:05 WARN]: 	at com.lishid.openinv.util.InternalAccessor.newSpecialEnderChest(InternalAccessor.java:196)
[17:36:05 WARN]: 	at com.lishid.openinv.OpenInv.getSpecialEnderChest(OpenInv.java:216)
[17:36:05 WARN]: 	at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:165)
[17:36:05 WARN]: 	at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34)
[17:36:05 WARN]: 	at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92)
[17:36:05 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:97)
[17:36:05 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:462)
[17:36:05 WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999)
[17:36:05 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[17:36:05 WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945)
[17:36:05 WARN]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760)
[17:36:05 WARN]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
[17:36:05 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

do you have any patch?

**Comment by Jikoo** [comment]
Need more information, but odds are on you're using a server implementation that is not a Spigot fork. OI uses Spigot's server mappings, you can't run it on a server implementation that does not provide those.

**Comment by FLORIAN4600** [comment]
Ok.
I use Mohist, and i just saw that mohist doesn't have spigot.
Thank for your responce.


// did you know if others mods/plugins for open an enderchest work at bukkit?

**Comment by FLORIAN4600** [comment]
I had found a plugin for open the ender chests.
Thanks for your help.
