### ISSUE TITLE
Release build for 1.19.1

### ISSUE THREAD

**Issue by soeinfachistdas** [Jikoo/OpenInv#91]
i have an error if i want to open a inventar, open ender still works.

[13:28:58 WARN]: java.lang.InstantiationException: Unable to create a new SpecialPlayerInventory
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:122)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:194)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:261)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:194)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:93)
[13:28:58 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:28:58 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:28:58 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[13:28:58 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[13:28:58 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[13:28:58 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[13:28:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[13:28:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:28:58 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:123)
[13:28:58 WARN]:        ... 12 more
[13:28:58 WARN]: Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.world.entity.player.EntityHuman.fB()'
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.internal.v1_19_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:71)
[13:28:58 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:28:58 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[13:28:58 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:28:58 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:28:58 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createObject(InternalAccessor.java:95)
[13:28:58 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:120)
[13:28:58 WARN]:        ... 12 more

**Comment by Jikoo** [comment]
https://github.com/Jikoo/OpenInv/releases/tag/4.2.1
