### ISSUE TITLE
1.19.1 /open error 

### ISSUE THREAD

**Issue by T4B999** [Jikoo/OpenInv#93]
[21:44:18 WARN]: java.lang.InstantiationException: Unable to create a new SpecialPlayerInventory
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:122)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:194)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:261)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:194)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:93)
[21:44:18 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:44:18 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:44:18 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1518)
[21:44:18 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[21:44:18 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1442)
[21:44:18 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1212)
[21:44:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[21:44:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:44:18 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:123)
[21:44:18 WARN]:        ... 12 more
[21:44:18 WARN]: Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.world.entity.player.EntityHuman.fB()'
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.internal.v1_19_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:71)
[21:44:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:44:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[21:44:18 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:44:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[21:44:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createObject(InternalAccessor.java:95)
[21:44:18 WARN]:        at OpenInv.jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:120)
[21:44:18 WARN]:        ... 12 more

**Comment by Jikoo** [comment]
Duplicate of #91
