### ISSUE TITLE
1.16.5 /openender error

### ISSUE THREAD

**Issue by StrictMaple** [Jikoo/OpenInv#97]
[18:23:45] [Server thread/WARN]: java.lang.InstantiationException: Unable to create a new ISpecialEnderChest: null
[18:23:45] [Server thread/WARN]: 	at com.lishid.openinv.util.InternalAccessor.newSpecialEnderChest(InternalAccessor.java:196)
[18:23:45] [Server thread/WARN]: 	at com.lishid.openinv.OpenInv.getSpecialEnderChest(OpenInv.java:216)
[18:23:45] [Server thread/WARN]: 	at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:165)
[18:23:45] [Server thread/WARN]: 	at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34)
[18:23:45] [Server thread/WARN]: 	at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92)
[18:23:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[18:23:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[18:23:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:998)
[18:23:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
[18:23:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:944)
[18:23:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:777)
[18:23:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265)
[18:23:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Jikoo** [comment]
The server implementation you're using has Forge mappings. OpenInv requires Craftbukkit server mappings.

In general, any of the Bukkit+Forge combination servers are a bad idea because plugins and mods do not interact well.
